backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

publish_mode: simple

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content/site.json"
        label: "Main Content"
        name: "content"
        format: "json"
        fields:
          - label: "Navigation"
            name: "nav"
            widget: "object"
            fields:
              - { label: "Subscribe Link (href)", name: "subscribe_href", widget: "string", default: "#subscribe" }

          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Hero Title", name: "title", widget: "string" }
              - { label: "Hero Subtitle", name: "subtitle", widget: "text" }

          - label: "Markets"
            name: "markets"
            widget: "object"
            fields:
              - { label: "Lead", name: "lead", widget: "text" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Blurb", name: "blurb", widget: "text" }
                  - { label: "Image (path)", name: "image", widget: "string", required: false }

          - label: "Subscribe Section"
            name: "subscribe"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", default: "Subscribe to Multifamily Max Invest" }
              - { label: "Lead", name: "lead", widget: "text" }
              - { label: "Button Label", name: "button_label", widget: "string", default: "Subscribe" }
              - { label: "Form Action URL", name: "form_action", widget: "string", default: "mailto:max@multifamily-max.com" }

          - label: "Services"
            name: "services"
            widget: "object"
            fields:
              - { label: "Lead", name: "lead", widget: "text" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Body", name: "body", widget: "text" }

          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Body", name: "body", widget: "text" }
              - label: "Bullets"
                name: "bullets"
                widget: "list"
                field: { label: "Bullet", name: "bullet", widget: "string" }
              - { label: "Photo (path)", name: "photo", widget: "string", default: "/assets/about.jpg" }
              - label: "CTA"
                name: "cta"
                widget: "object"
                fields:
                  - { label: "Label", name: "label", widget: "string", default: "Contact Us" }
                  - { label: "Href", name: "href", widget: "string", default: "#contact" }

          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Intro text", name: "intro", widget: "text", default: "Contact us today for any of your multifamily needs. We're here to help!" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Phone (link)", name: "phone", widget: "string" }
              - { label: "Phone (display)", name: "phone_display", widget: "string" }
              - { label: "Submit Label", name: "submit_label", widget: "string", default: "Send" }
